name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  get: ^4.6.6
  get_cli: ^1.8.1
  msh_checkbox: ^2.0.1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_messaging: ^15.0.4
  shared_preferences: ^2.3.2
  google_sign_in: ^6.2.1
  elegant_notification: ^2.2.2
  package_info_plus: ^8.0.2
  url_launcher: ^6.3.0
  http: ^1.2.2
  webview_flutter: ^4.8.0
  lottie: ^3.1.2
  firebase_crashlytics: ^4.1.1


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icon/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100

    - family: Altoysitalicpersonalonly
      fonts:
        - asset: assets/fonts/Altoysitalicpersonalonly.ttf

    - family: DINNextLTPro
      fonts:
        - asset: assets/fonts/DINNextLTPro-Medium.ttf
          weight: 500
